### ISSUE TITLE
[Discussions] About frametime anomaly after unlocking fps in 4.0

### ISSUE THREAD

**Issue by CirnoSalt** [34736384/genshin-fps-unlock#215]
![image](https://github.com/34736384/genshin-fps-unlock/assets/23478997/492eedc4-0faf-4a2f-9684-706792c77425)

I've noticed that after the Genshin 4.0 update all fps unlocking tools are experiencing screen lag issues caused by frametime fluctuations.
  
This lag is very disruptive to the gaming experience and there seems to be no way to ask HoYoverse to fix the issue officially as it only occurs after using the fps unlocker, and observing the fps values does not reveal the problem.
  
However, I've noticed that some Apple devices have the 120fps option opened by the official (e.g. M1/M2 iPad Pro, iPhone 13 Pro...)！
  
so I'm collecting feedback from users who are using these devices, and whether those who are using them are experiencing similar screen lag and latency issues after turning on the 120fps mode, the If the problem exists in the same way, there is a good reason to submit feedback on this issue to HoYoverse officials!

**Comment by Spedemix** [comment]
I managed to fix my stuttering issues by lowering the rendering resolution down from 1.1 to 1.0, despite my game being seemingly CPU-limited at all times.

So the stutters might occur because of some bottlenecks, play around with settings to see whether it'll alleviate the stuttering.

**Comment by CirnoSalt** [comment]
> I managed to fix my stuttering issues by lowering the rendering resolution down from 1.1 to 1.0, despite my game being seemingly CPU-limited at all times.
> 
> So the stutters might occur because of some bottlenecks, play around with settings to see whether it'll alleviate the stuttering.

Testing on my device (NVIDIA 3060ti GPU), there is still noticeable lag at a rendering resolution of 1.0, which doesn't ease up until it's lowered to 0.6, but by that point the game screen is very blurry ...... The same settings (rendering resolution 1.0) were used in previous versions without any performance Problems.

**Comment by bean789** [comment]
same problem here. bad frametimes until i run 0.6 res

**Comment by BlueStarBRS** [comment]
> 
> ![image](https://github.com/34736384/genshin-fps-unlock/assets/23478997/492eedc4-0faf-4a2f-9684-706792c77425)
> 
> I've noticed that after the Genshin 4.0 update all fps unlocking tools are experiencing screen lag issues caused by frametime fluctuations.
>   
> This lag is very disruptive to the gaming experience and there seems to be no way to ask HoYoverse to fix the issue officially as it only occurs after using the fps unlocker, and observing the fps values does not reveal the problem.
>   
> However, I've noticed that some Apple devices have the 120fps option opened by the official (e.g. M1/M2 iPad Pro, iPhone 13 Pro...)！
>   
> so I'm collecting feedback from users who are using these devices, and whether those who are using them are experiencing similar screen lag and latency issues after turning on the 120fps mode, the If the problem exists in the same way, there is a good reason to submit feedback on this issue to HoYoverse officials!

Update your gpu driver.
On Default Genshin there many new instability issues like the map so it just takes time i guess also Update your gpu driver anytime if there is a new Version. I have seen mihoyo roled after Release 2-4 ingame hitfix Updates so there will come save more at least i think its maybe better with the next 4.1 update mabye.

**Comment by BlueStarBRS** [comment]
Btw you can lower the issue with disable vsync or by turning it on  and render Resolution is a thing what csn help 

There some Settings who i recommend to let it disabled:

Volumespread,
Motionblur,
If your game is to blurry for you Take FSR instat of MSAA

Mabye i can help :)

**Comment by Spedemix** [comment]
Folks who've managed to "fix" the issue by lowering rendering resolution (1.0, 0.6 etc): What is your native rendering resolution and GPU? 

I'm running RTX 4060 with 1440p and 1.0 rendering resolution helped my stuttering tremendeously

**Comment by CirnoSalt** [comment]
> Folks who've managed to "fix" the issue by lowering rendering resolution (1.0, 0.6 etc): What is your native rendering resolution and GPU?
> 
> I'm running RTX 4060 with 1440p and 1.0 rendering resolution helped my stuttering tremendeously

My native resolution is 2160P and I need to reduce it to 0.6 to alleviate the lag (3060ti GPU), and have recently discovered that the lag only occurs on Fontaine maps and not in other countries…🤔

**Comment by CirnoSalt** [comment]
> Btw you can lower the issue with disable vsync or by turning it on and render Resolution is a thing what csn help
> 
> There some Settings who i recommend to let it disabled:
> 
> Volumespread, Motionblur, If your game is to blurry for you Take FSR instat of MSAA
> 
> Mabye i can help :)

Thanks for your suggestion!
I tried turning Vsync on/off and upgrading the GPU driver to the latest version, and the problem still persists :(, turning on FSR does improve the experience at low rendering resolutions, but the quality of the image at the "0.6" level is still far from the original resolution.
It was found that this glitch only occurs in Fontaine maps, so I guess we'll have to wait for the next version of the game to fix this issue.

**Comment by CirnoSalt** [comment]
> > ![image](https://user-images.githubusercontent.com/23478997/263032162-492eedc4-0faf-4a2f-9684-706792c77425.png)
> > I've noticed that after the Genshin 4.0 update all fps unlocking tools are experiencing screen lag issues caused by frametime fluctuations.
> > This lag is very disruptive to the gaming experience and there seems to be no way to ask HoYoverse to fix the issue officially as it only occurs after using the fps unlocker, and observing the fps values does not reveal the problem.
> > However, I've noticed that some Apple devices have the 120fps option opened by the official (e.g. M1/M2 iPad Pro, iPhone 13 Pro...)！
> > so I'm collecting feedback from users who are using these devices, and whether those who are using them are experiencing similar screen lag and latency issues after turning on the 120fps mode, the If the problem exists in the same way, there is a good reason to submit feedback on this issue to HoYoverse officials!
> 
> Update your gpu driver. On Default Genshin there many new instability issues like the map so it just takes time i guess also Update your gpu driver anytime if there is a new Version. I have seen mihoyo roled after Release 2-4 ingame hitfix Updates so there will come save more at least i think its maybe better with the next 4.1 update mabye.

Update: 4.1 not fix :(

**Comment by bean789** [comment]
> > > ![image](https://user-images.githubusercontent.com/23478997/263032162-492eedc4-0faf-4a2f-9684-706792c77425.png)
> > > I've noticed that after the Genshin 4.0 update all fps unlocking tools are experiencing screen lag issues caused by frametime fluctuations.
> > > This lag is very disruptive to the gaming experience and there seems to be no way to ask HoYoverse to fix the issue officially as it only occurs after using the fps unlocker, and observing the fps values does not reveal the problem.
> > > However, I've noticed that some Apple devices have the 120fps option opened by the official (e.g. M1/M2 iPad Pro, iPhone 13 Pro...)！
> > > so I'm collecting feedback from users who are using these devices, and whether those who are using them are experiencing similar screen lag and latency issues after turning on the 120fps mode, the If the problem exists in the same way, there is a good reason to submit feedback on this issue to HoYoverse officials!
> > 
> > 
> > Update your gpu driver. On Default Genshin there many new instability issues like the map so it just takes time i guess also Update your gpu driver anytime if there is a new Version. I have seen mihoyo roled after Release 2-4 ingame hitfix Updates so there will come save more at least i think its maybe better with the next 4.1 update mabye.
> 
> Update: 4.1 not fix :(

yes sadly it's not fixed. 
running 4k at 0.6 resolution with fsr minimizes the stutter, although it's still there. using a 3080. stutter triggers after diving underwater.
I hope this somehow gets fixed because at these settings my GPU is very under utilized and the game is blurry.

**Comment by RahuX** [comment]
Doing some testing on my end, and the two biggest settings to change to alleviate this are either the resolution scale as mentioned before, or disabling Global Illumination entirely. Changing other settings has no effect.

Disabling GI does get rid of the random frametime spikes for me, but obviously at the cost of the lighting in the game looking very flat. All other GI settings result in the frametime spikes.

I can't really tell if the issue is due to high GPU usage causing these spikes (which lowering the res or disabling GI alleviates), or if it's actually just related to GI (maybe the game's GI pass has some optimization issues when going underwater that don't get cleared up when surfacing).

Also the game really doesn't seem to like running above 120 FPS as well. At least the frametime spikes are more prevalent above 120, so I'd recommend capping the game to 120. Again, could just be high GPU utilization (above 90%) making these issues crop up (which a lower framerate cap tamps down usage).

For now, given 0.8 scale with FSR2 looks pretty close to native res 1440p for me (what I play at), I think I'll just stick with that.

**Comment by bean789** [comment]
> Also the game really doesn't seem to like running above 120 FPS as well. At least the frametime spikes are more prevalent above 120, so I'd recommend capping the game to 120. Again, could just be high GPU utilization (above 90%) making these issues crop up (which a lower framerate cap tamps down usage).

It really does seem like the more GPU headroom there is, the more the stutter is minimized. with my 3080 at around 50% usage due to fsr, the stutter is ALMOST non-existent. I've been considering a GPU upgrade from 3080 -> 4080 due to this. What an odd bug.

How unfortunate it is that their deal with Apple of high framerate exclusivity on IOS only, means this issue might never get fixed since I doubt anyone wants to run genshin higher than 60 fps on their mobile device due to extreme battery drain and heating issues. Maybe some hero can get hoyo to fix this.

**Comment by RahuX** [comment]
> > Also the game really doesn't seem to like running above 120 FPS as well. At least the frametime spikes are more prevalent above 120, so I'd recommend capping the game to 120. Again, could just be high GPU utilization (above 90%) making these issues crop up (which a lower framerate cap tamps down usage).
> 
> It really does seem like the more GPU headroom there is, the more the stutter is minimized. with my 3080 at around 50% usage due to fsr, the stutter is ALMOST non-existent. I've been considering a GPU upgrade from 3080 -> 4080 due to this. What an odd bug.
> 
> How unfortunate it is that their deal with Apple of high framerate exclusivity on IOS only, means this issue might never get fixed since I doubt anyone wants to run genshin higher than 60 fps on their mobile device due to extreme battery drain and heating issues. Maybe some hero can get hoyo to fix this.

Kokomi used to have issues with her NAs severely lagging the game, but only above 60 FPS, so it took people having to confirm it was an issue on their 120 FPS supported iOS devices as well and submitting bug reports of it to Hoyo to get them to eventually fix it.

If this issue is present under the same conditions (really just above 60 FPS on iOS), the same could be done here and hopefully it will be fixed.

However, given the Kokomi issue was regarding the usability of a character, and this is more just inconsistent frametimes causing non optimal feel and visual response, it may be a lower priority issue for them to fix.

**Comment by CirnoSalt** [comment]
Update: 4.2 not fix :( :(

**Comment by bean789** [comment]
> Update: 4.2 not fix :( :(

yeah very lame. I guess not enough people report it to mihoyo or it doesn't happen on iOS ??

**Comment by RahuX** [comment]
Game just got a small update today. I decided to change my res scale back to 1.0 just out of curiosity to test it (been running at 0.8 to not suffer from the frametime issues), and I don't seem to be having the severe frametime spikes anymore.

Tested in all the usual places, and the visual presentation still seems smooth for me despite GPU usage higher than 90%.

Don't wanna jinx it, and could use further testing, but at least on my end, this issue seems fixed now.

**Comment by CirnoSalt** [comment]
> Game just got a small update today. I decided to change my res scale back to 1.0 just out of curiosity to test it (been running at 0.8 with a cap at 120 FPS to not suffer from the frametime issues), and I don't seem to be having the severe frametime spikes anymore. At 1.0 res scale, and with a 144 FPS cap.
> 
> Tested in all the usual places that would trigger this before for me, obviously going underwater to trigger it, and the visual presentation still seems smooth for me both on and below the surface, despite GPU usage higher than 90%. There's some small frametime spikes, but those are mostly just from the game not matching the FPS cap, and are nowhere near the level they were before (not visually noticeable anyway).
> 
> Don't wanna jinx it, and could use further testing, but at least on my end, this issue seems fixed now.

![QQ截图20231111135409](https://github.com/34736384/genshin-fps-unlock/assets/23478997/8e2d57ac-9472-45c6-acac-b0e84805f56d)
What is the resolution of the monitor you are using? On the resolution I'm using (2160P+1.0) this issue still exists and did not receive a new patch update for the game today ......🤔

**Comment by CirnoSalt** [comment]
Conclusions that have been gathered so far:
- This issue affects all current fps unlocking tools, as they all work basically the same way.

- The higher the display and rendering resolution, the worse it is affected.

- After my own testing adjusting other display options does not alleviate this glitch.
(Some feedback says turning off GI/shadows may fix the problem)

- This issue only affects parts of the Fontaine map. (Most indoor scenes do not have the problem)

- The lag is more noticeable if the framerate unlock limit exceeds 90/120fps.

- HoYoverse officially doesn't look like they want to fix this issue, as 120fps users with ios devices don't seem to be affected.

It may take a more capable developer to make invasive changes to the game if this latency is to be fixed ......

**Comment by RahuX** [comment]
> > Game just got a small update today. I decided to change my res scale back to 1.0 just out of curiosity to test it (been running at 0.8 with a cap at 120 FPS to not suffer from the frametime issues), and I don't seem to be having the severe frametime spikes anymore. At 1.0 res scale, and with a 144 FPS cap.
> > Tested in all the usual places that would trigger this before for me, obviously going underwater to trigger it, and the visual presentation still seems smooth for me both on and below the surface, despite GPU usage higher than 90%. There's some small frametime spikes, but those are mostly just from the game not matching the FPS cap, and are nowhere near the level they were before (not visually noticeable anyway).
> > Don't wanna jinx it, and could use further testing, but at least on my end, this issue seems fixed now.
> 
> ![QQ截图20231111135409](https://user-images.githubusercontent.com/23478997/282222321-8e2d57ac-9472-45c6-acac-b0e84805f56d.png) What is the resolution of the monitor you are using? On the resolution I'm using (2160P+1.0) this issue still exists and did not receive a new patch update for the game today ......🤔

1440p. For reference, running the game at a 1.0 res scale would always produce the frametime issues for me after going underwater. Lowering it to 0.8, and capping the FPS to 120 FPS instead of 144 FPS would usually be just enough to fix it (or running the game at 1.0 with a 90 FPS cap).

Now? I'm not getting it anymore. Running at 1.0 res scale with a 144 FPS cap.

And the update I got was ~200MB. Downloaded while logging in. Via process of elimination, I figure it has to be this update, as the last NVIDIA driver update didn't fix things, and I was still experiencing the frametime issues the day before this update dropped.

The only thing I could think of is it could be in relation to GPU usage still. Before I was getting the issues basically any time Special K was reporting 90% usage or more. Now, while I'm not reaching 100% usage, usage in the 90s yields no anomalies. For reference, my GPU is a 2070 Super.

4K is pretty demanding to run in general, especially at higher framerates, so unless you have an absolute beast of a GPU, it's probably being absolutely hammered I would assume (even for a game like Genshin), which is maybe why these issues are still cropping up for you.

**Comment by RahuX** [comment]
Ok. Further testing does show that actually, you are right, but, **I did find what basically alleviated the frametime spikes for me.**

I recently decided to enable the NVIDIA Low Latency + Boost setting in Special K. Doing some quick testing with it on and off, and yep, basically no more frametime spikes with it enabled. This also applies with just the NVIDIA Low Latency setting, you don't need boost.

Here are the results, tested at an area that always triggered the frametime spikes for me.

NVIDIA Low Latency + Boost Off (should look familiar):
![image](https://github.com/34736384/genshin-fps-unlock/assets/5471553/ab7f0e50-ecf6-4879-9da5-1074f745ac98)


NVIDIA Low Latency + Boost On:
![image](https://github.com/34736384/genshin-fps-unlock/assets/5471553/eeb72d6c-8079-4bfb-bbec-2699e7affc6e)



And just to be as transparent as possible, this is the absolute worst I saw for frametime spikes with it enabled.
![image](https://github.com/34736384/genshin-fps-unlock/assets/5471553/137d781a-8b8a-471a-902f-04e6edcaab27)




This is also regardless of res scale or global illumination setting.

As this is a setting that can also be applied via the NVIDIA Control Panel/NVIDIA Inspector, theoretically, enabling NVIDIA Low Latency (setting it to Ultra in the Control Panel) should produce the same effect if you don't want to use Special K. I'll do some tests on that when I get the chance

**Comment by bean789** [comment]
> Ok. Further testing does show that actually, you are right, but, **I did find what basically alleviated the frametime spikes for me.**
Bro you are a genius. You are right! Using low latency on ultra in nvidia control panel: at 4k the frametime stutters are smaller! It doesnt entirely remove the stutter at native... but I can now run 0.8 fsr and get very minimal stutter. before I had to run 0.6. There is 100% a difference in the frame time graph of rtss and in the perceived stutter!

Unfortunately I dont think I can run special k since i use 3dmigoto for mods... I would love to get the performance you got with special k... but I believe these two programs should conflict ?? Do you run 3dmigoto gimi with special k at the same time?

Thanks for your findings! I am very happy to be able to get some resolution back.

**Comment by CirnoSalt** [comment]
> > Conclusions that have been gathered so far:
> > ```
> > * This issue affects all current fps unlocking tools, as they all work basically the same way.
> > 
> > * The higher the display and rendering resolution, the worse it is affected.
> > 
> > * After my own testing adjusting other display options does not alleviate this glitch.
> >   (Some feedback says turning off GI/shadows may fix the problem)
> > 
> > * This issue only affects parts of the Fontaine map. (Most indoor scenes do not have the problem)
> > 
> > * The lag is more noticeable if the framerate unlock limit exceeds 90/120fps.
> > 
> > * HoYoverse officially doesn't look like they want to fix this issue, as 120fps users with ios devices don't seem to be affected.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It may take a more capable developer to make invasive changes to the game if this latency is to be fixed ......
> 
> Ok. Further testing does show that actually, you are right, but, **I did find what basically alleviated the frametime spikes for me.**
> 
> I recently decided to enable the NVIDIA Low Latency + Boost setting in Special K. Doing some quick testing with it on and off, and yep, basically no more frametime spikes with it enabled. This also applies with just the NVIDIA Low Latency setting, you don't need boost.
> 
> Here are the results, tested at an area that always triggered the frametime spikes for me.
> 
> NVIDIA Low Latency + Boost Off (should look familiar): ![image](https://user-images.githubusercontent.com/5471553/282253163-ab7f0e50-ecf6-4879-9da5-1074f745ac98.png)
> 
> NVIDIA Low Latency + Boost On: ![image](https://user-images.githubusercontent.com/5471553/282253220-eeb72d6c-8079-4bfb-bbec-2699e7affc6e.png)
> 
> And just to be as transparent as possible, this is the absolute worst I saw for frametime spikes with it enabled. ![image](https://user-images.githubusercontent.com/5471553/282253324-137d781a-8b8a-471a-902f-04e6edcaab27.png)
> 
> This is also regardless of res scale or global illumination setting.
> 
> As this is a setting that can also be applied via the NVIDIA Control Panel/NVIDIA Inspector, I also tried it out by setting it to "Ultra" in the NVIDIA control panel for Genshin. The results are technically better, but not as good as Special K's implementation
> 
> This is the worst I got with it set to Ultra in the control panel, but disabled in Special K: ![image](https://user-images.githubusercontent.com/5471553/282253910-1362b216-bc5e-41c3-9341-7e83b2ca7f3f.png)
> 
> So the conclusion here is, if you are willing to use Special K for Genshin (you'll have to use the global injector because of the game's anti-cheat), if you enable NVIDIA Low Latency in Special K, it basically alleviates these anomalies. Otherwise (you don't want to use Special K, or you have an AMD GPU), this can be somewhat alleviated by changing the low latency setting to its best setting in your control panel.
> 
> That is an assumption for AMD GPUs though. To anyone who has an AMD GPU, I'm curious as to if you're also getting these frametime spikes, and if so, if setting your low latency setting (should be named "AMD Anti-Lag") to its best setting also helps to alleivate this.

Thank you very much for your efforts, Bro!
I enabled the low latency mode for the Genshin process in the NVIDIA control panel, and now even if it is located in an underwater scene frametime is still flat, just like before!👍
My PC configuration is:
CPU: Ryzen 5900X
GPU: NVIDIA 3060ti GDDR6X

![{EE76BE59-AF57-44a0-A66A-F454F7318123}](https://github.com/34736384/genshin-fps-unlock/assets/23478997/61752949-fb80-4f01-8e6b-56532423ff33)
  
![QQ截图20231112153415](https://github.com/34736384/genshin-fps-unlock/assets/23478997/8ca210cb-04af-40e6-a199-719c7021542d)

**Comment by RahuX** [comment]
> > Ok. Further testing does show that actually, you are right, but, **I did find what basically alleviated the frametime spikes for me.**
> 
> Bro you are a genius. You are right! Using low latency on ultra in nvidia control panel: at 4k the frametime stutters are smaller! It doesnt entirely remove the stutter at native... but I can now run 0.8 fsr and get very minimal stutter. before I had to run 0.6. There is 100% a difference in the frame time graph of rtss and in the perceived stutter!
> 
> Unfortunately I dont think I can run special k since i use 3dmigoto for mods... I would love to get the performance you got with special k... but I believe these two programs should conflict ?? Do you run 3dmigoto gimi with special k at the same time?
> 
> Thanks for your findings! I am very happy to be able to get some resolution back.

I do not use both, as I don't really mod my Genshin outside of the FPS Unlocker and Special K (and I really only started using Special K because Genshin doesn't have proper DXGI Flip Model support which barred me from taking full advantage of VRR on Windows 10).

A quick search of this question online yields mixed results. You _should_ be able to run both in theory, but both do a lot of similar things, so there could be some interference/conflicts. If you do decide to try to use both, make sure that Special K is the global injector version (otherwise the game just deletes its DLLs), and since Genshin requires admin privileges to be run, Special K also needs to be run as admin alongside Genshin.

**Comment by SatoruASH** [comment]
I am having my fps dropped to 35 and frametime in a fixed time period to 33ms,I use low latency on ultra in NVIDIA control panel so what should I do ?

**Comment by BlueStarBRS** [comment]
> Conclusions that have been gathered so far:
> 
> * This issue affects all current fps unlocking tools, as they all work basically the same way.
> * The higher the display and rendering resolution, the worse it is affected.
> * After my own testing adjusting other display options does not alleviate this glitch.
>   (Some feedback says turning off GI/shadows may fix the problem)
> * This issue only affects parts of the Fontaine map. (Most indoor scenes do not have the problem)
> * The lag is more noticeable if the framerate unlock limit exceeds 90/120fps.
> * HoYoverse officially doesn't look like they want to fix this issue, as 120fps users with ios devices don't seem to be affected.
> 
> It may take a more capable developer to make invasive changes to the game if this latency is to be fixed ......

so basicaly a typical bug with new game content dont forgett the game is not programmed for uncapped fps dont forget that.

**Comment by BlueStarBRS** [comment]
> I am having my fps dropped to 35 and frametime in a fixed time period to 33ms,I use low latency on ultra in NVIDIA control panel so what should I do ?

dont use ultra turn it off or only "on" more cpu usage is caused by this and kills your fps even more for almost nothing also you dont need low ms in genshin.

**Comment by kekkoflop** [comment]
5.0 no fix :(

**Comment by CirnoSalt** [comment]
> 5.0 no fix :(

Enable AMD Anti-Lag & NVIDIA Ultra-Low Latency mode，I solved this problem by turning on these GPU features.

**Comment by a4840639** [comment]
Just a reminder, always turn off in-game vsync when using this unlocker.
I was having high frame time (14ms-ish for 120fps) and also some weird jittering/jump back during some scenarios (e.g. aiming with element skill when using character like Yaoyao/Keqing. Similar jittery can also be seen on the shadows when forwarding the time). The game also did not feel any more responsive than the 60FPS capped PS5 version.
Today, I realized I was keeping the in-game v-sync on and all the issues are gone as soon I turned it off, the game is instantly more responsive despite I never had any issue reaching 120fps on my rig.
