### ISSUE TITLE
Frequent and very distracting stuttering

### ISSUE THREAD

**Issue by Jamen1** [34736384/genshin-fps-unlock#50]
At high fps game hickups massively every 10 seconds or so, no matter what I'm doing. Tried every fix I could possibly think of and I'm running on a high end system. Any possible fixes or thoughts? I think it's just a Unity 2017 issue but I don't see anyone else saying they have this issue. It's very distracting during gameplay and really takes me out of the immersion... (P.S. in rivatuner you can see big spikes in the frametime graph with 20 fps drops whenever it happens)

**Comment by Ryrin45** [comment]
I came here to see if anyone else had noticed this. I swear it feels worse now than it's ever been. Every 10 seconds or so there's a massive frametime spike that causes a very distracting stutter. I've been playing since launch and while it's always had an issue with these hitches, I don't remember it being frequent and regular like this.

**Comment by system2ckc** [comment]
So I've been trying every single solution in the book for over 2 days now. This game has a periodic stutter that seems to be tied to framerate. Essentially at 120 fps you will get this periodic stutter at twice the speed of 60 fps. But regardless, the game has stutter no matter what you do at set intervals. 

From my testing, at least idle at Mondstadt fountain, I've found the rate was roughly 17.5-20 seconds @ 120fps, and 35-40 seconds @ 60fps. This timing changes depending on what your doing but I'm pretty sure relativity is consistent. So essentially the higher the framerate, the faster this stutter occurs. I flipped between 60 and 120 cap on RTSS for my testing, so it isn't just a case of the mod causing the stutter. There's probably nothing the mod author can do since this seems to be a Genshin problem. I've also tested on Ps5, which also seems to have this periodic stutter. However, the ps5 seems to handle stutter-recovery a lot better so it doesn't feel as jarring as PC stutters. 

The game also has stutters not related to timing that happens whenever you finish talking to npc, scrolling through the big map, opening the map, etc. 

I can't say for certain if this periodic stutter was in previous versions of Genshin. Both my old gpu and my new gpu were able to play Genshin at a locked 60 but maybe because I've been benchmarking my games lately I only just now notice the stuttering to this degree. But personally, I do kind of feel like stuttering is worse this patch than it ever has been. It could have started last patch though, I barely played 2.3. 

P.S just read Ryrin45's post, yeah that pretty much lines up with how I feel about it. I don't think the stutter was this frequent in previous patches either.

**Comment by Jamen1** [comment]
I'm experiencing the exact same thing as you two, it's periodic and seems to happen more frequently at higher framerates (and more jarring but that might be from the smoother frames normally). Must not be a mod issue but if anyone figures out anything please comment here, otherwise we should complain to Mihoyo.

**Comment by Ryrin45** [comment]
Hard to know for sure, but the leading theory is that it's related to how Unity engine does garbage collection. This was apparently addressed in later version of Unity, but Mihoyo is either not using a new enough version or isn't using the fix. If this is what's causing it then there's nothing we can do but hope for a fix from Mihoyo.

**Comment by DAOWAce** [comment]
> I can't say for certain if this periodic stutter was in previous versions of Genshin. 

Sure as hell was.

It's been a problem since the game's release, and made worse in the 1.1 update which forced a lot of texture re-streaming because of low-end devices being hampered by their lack of RAM.  Just google, search reddit, etc., and people have been complaining about this issue for well over a year.

I haven't tried this tool to see if it affects the framerate in a different way, nor have I tried it after 2.4 due to the anti-cheat update (not risking my OG account and I'm done testing anything on this game), but it must definitely be more frequent at higher framerates, as the times I've played at its locked 60, the issue is less severe, but still quite common.

The devs don't care about anything but money.  Updating to a newer build of Unity, or doing anything to adjust the GC, will most likely never be done, as it doesn't make them money.  Hell, they haven't even improved the camera control when aiming; it's still a juddery (and mouse accelerated) mess because of how they programmed it

I've not actually playtested Honkai Impact (their previous game, also on PC, with 90/120FPS options), but it should also be running on Unity if anyone wants to see if it suffers the GC stutter.

**Comment by system2ckc** [comment]
So today they released an update to greatly lower the amount of stutters that happen. I did some minor testing for now but it at the Fountain I went from the previous 35 second intervals to a whole Minute and 40 seconds. Thats about a 150% decrease in stutters which is fantastic. Stutters after talking to npcs, and panning map are also greatly lessened. Im not too sure about the recovery and intensity of the stutters themselves though. Might be about the same. But just having vastly less amounts of stutter is a great step. I don't think ima test the High Framerate stuff for awhile so if anyone else wants to follow up that'd be great. Mainly see if the stutter intervals are more frequent with higher framerates or if it's still the same regardless of framerate now.

**Comment by Ryrin45** [comment]
> So today they released an update to greatly lower the amount of stutters that happen. I did some minor testing for now but it at the Fountain I went from the previous 35 second intervals to a whole Minute and 40 seconds. Thats about a 150% decrease in stutters which is fantastic. Stutters after talking to npcs, and panning map are also greatly lessened. Im not too sure about the recovery and intensity of the stutters themselves though. Might be about the same. But just having vastly less amounts of stutter is a great step. I don't think ima test the High Framerate stuff for awhile so if anyone else wants to follow up that'd be great. Mainly see if the stutter intervals are more frequent with higher framerates or if it's still the same regardless of framerate now.

It seems they increased the time between the stutters. So now at 60fps it's anywhere from 2 to 3 minutes between stutters. The problem is the issue is still tied to framerate. So the rate of stutters still basically doubles at 120fps. While I appreciate that they did anything at all, it seems more like a band-aid rather than a real fix. I hope they have a more complete fix planned for later.

**Comment by Jamen1** [comment]
The stutters have improved for sure. It's nice to know the Genshin team are at least aware of it and trying to fix it, but I hope there's more coming. I have to admit however, the stutters have become far less noticable in my gameplay, and I'm enjoying the game just a bit more. The stutters that still occur also seem to be a lot less jarring and they don't always distract me anymore.

**Comment by system2ckc** [comment]
> > So today they released an update to greatly lower the amount of stutters that happen. I did some minor testing for now but it at the Fountain I went from the previous 35 second intervals to a whole Minute and 40 seconds. Thats about a 150% decrease in stutters which is fantastic. Stutters after talking to npcs, and panning map are also greatly lessened. Im not too sure about the recovery and intensity of the stutters themselves though. Might be about the same. But just having vastly less amounts of stutter is a great step. I don't think ima test the High Framerate stuff for awhile so if anyone else wants to follow up that'd be great. Mainly see if the stutter intervals are more frequent with higher framerates or if it's still the same regardless of framerate now.
> 
> It seems they increased the time between the stutters. So now at 60fps it's anywhere from 2 to 3 minutes between stutters. The problem is the issue is still tied to framerate. So the rate of stutters still basically doubles at 120fps. While I appreciate that they did anything at all, it seems more like a band-aid rather than a real fix. I hope they have a more complete fix planned for later.
> 
> Though I can't comment on the severity of the stutters themselves yet. I'll have to play more and see if they feel as bad.

Damn, yeah i figured it would still be tied to framerate. I guess maybe though it would atleast be playable status now even with high framerate. Maybe compromise @ 100fps or something wouldn't be too bad too instead of 120. Il give it a try AFTER I claim my Lantern Rite char. Not that I expect anyone to get banned for using this mod but... just in case.

**Comment by ZEFIR001** [comment]
Same here,but i noticed that decreasing Crowd Density and GPU load helps a lot. Clearly game optimization issue. It is also overloading the USB devices somehow because only playing genshin cause wdf100sys to spike up and audio stutters or disappears.
